export const collegeFootballRivalries = {
	"Air Force": ["Army", "Colorado State", "Hawaii", "Navy"],
	Akron: ["Kent State"],
	Alabama: ["Auburn", "LSU", "Mississippi State", "Tennessee"],
	"Appalachian State": ["Charlotte", "Georgia Southern"],
	Arizona: ["Arizona State", "New Mexico"],
	"Arizona State": ["Arizona"],
	Arkansas: ["LSU", "Missouri", "Texas", "Texas A&M"],
	"Arkansas State": ["Memphis"],
	Army: ["Air Force", "Navy", "Notre Dame"],
	Auburn: ["Alabama", "Florida", "Georgia", "LSU"],
	"Ball State": ["Miami (OH)", "Northern Illinois"],
	Baylor: ["TCU", "Texas A&M", "Texas Tech"],
	"Boise State": ["Fresno State", "Nevada"],
	"Boston College": ["Clemson", "Massachusetts", "Notre Dame", "Syracuse"],
	"Bowling Green": ["Kent State", "Toledo"],
	Buffalo: ["Temple"],
	BYU: ["Utah", "Utah State", "Wyoming"],
	California: ["Stanford", "UCLA"],
	"Central Michigan": ["Eastern Michigan", "Western Michigan"],
	Charlotte: ["Appalachian State", "Old Dominion"],
	Cincinnati: ["Louisville", "Memphis", "Miami (OH)", "Pittsburgh", "UCF"],
	Clemson: [
		"Boston College",
		"Florida State",
		"Georgia",
		"Georgia Tech",
		"NC State",
		"South Carolina",
	],
	"Coastal Carolina": ["Liberty"],
	Colorado: ["Colorado State", "Nebraska", "Utah"],
	"Colorado State": ["Air Force", "Colorado", "Wyoming"],
	Connecticut: ["Massachusetts", "UCF"],
	Duke: ["North Carolina", "NC State", "Wake Forest"],
	"East Carolina": ["Marshall", "North Carolina", "NC State"],
	"Eastern Michigan": ["Central Michigan", "Western Michigan"],
	Florida: [
		"Auburn",
		"Florida State",
		"Georgia",
		"LSU",
		"Miami (FL)",
		"Tennessee",
	],
	"Florida Atlantic": ["Florida International"],
	"Florida International": ["Florida Atlantic"],
	"Florida State": ["Clemson", "Florida", "Miami (FL)"],
	"Fresno State": [
		"Boise State",
		"Hawaii",
		"San Diego State",
		"San Jose State",
	],
	Georgia: [
		"Auburn",
		"Clemson",
		"Florida",
		"Georgia Tech",
		"South Carolina",
		"Tennessee",
	],
	"Georgia Southern": ["Appalachian State", "Georgia State"],
	"Georgia State": ["Georgia Southern", "Kennesaw State"],
	"Georgia Tech": ["Clemson", "Georgia", "Vanderbilt", "Virginia Tech"],
	Hawaii: ["Air Force", "Fresno State", "San Jose State", "UNLV", "Wyoming"],
	Houston: ["Rice", "Tulsa"],
	Illinois: ["Missouri", "Northwestern", "Ohio State", "Purdue"],
	Indiana: ["Kentucky", "Michigan State", "Purdue"],
	Iowa: ["Iowa State", "Minnesota", "Nebraska", "Wisconsin"],
	"Iowa State": ["Iowa", "Kansas State", "Missouri"],
	"Jacksonville State": ["Troy"],
	"James Madison": ["Old Dominion"],
	Kansas: ["Kansas State", "Missouri"],
	"Kansas State": ["Iowa State", "Kansas"],
	"Kennesaw State": ["Georgia State"],
	"Kent State": ["Akron", "Bowling Green"],
	Kentucky: ["Indiana", "Louisville", "Tennessee", "Vanderbilt"],
	Liberty: ["Coastal Carolina", "Old Dominion"],
	Louisiana: ["Louisiana Tech", "Louisiana-Monroe"],
	"Louisiana Tech": ["Louisiana", "Louisiana-Monroe", "Southern Mississippi"],
	"Louisiana-Monroe": ["Louisiana", "Louisiana Tech"],
	Louisville: ["Cincinnati", "Kentucky", "Memphis", "West Virginia"],
	LSU: [
		"Alabama",
		"Arkansas",
		"Auburn",
		"Florida",
		"Mississippi State",
		"Ole Miss",
		"Texas A&M",
		"Tulane",
	],
	Marshall: ["East Carolina", "Ohio", "West Virginia"],
	Maryland: ["Navy", "Penn State", "Rutgers", "Virginia"],
	Massachusetts: ["Boston College", "Connecticut"],
	Memphis: [
		"Arkansas State",
		"Cincinnati",
		"Louisville",
		"Ole Miss",
		"Southern Mississippi",
		"UAB",
	],
	"Miami (FL)": ["Florida", "Florida State", "Virginia Tech"],
	"Miami (OH)": ["Ball State", "Cincinnati", "Ohio"],
	Michigan: [
		"Michigan State",
		"Minnesota",
		"Northwestern",
		"Notre Dame",
		"Ohio State",
	],
	"Michigan State": ["Indiana", "Michigan", "Notre Dame", "Penn State"],
	"Middle Tennessee": ["Troy", "Western Kentucky"],
	Minnesota: ["Iowa", "Michigan", "Nebraska", "Penn State", "Wisconsin"],
	"Mississippi State": ["Alabama", "LSU", "Ole Miss"],
	Missouri: [
		"Arkansas",
		"Illinois",
		"Iowa State",
		"Kansas",
		"Nebraska",
		"Oklahoma",
		"South Carolina",
	],
	Navy: ["Air Force", "Army", "Maryland", "Notre Dame", "SMU"],
	Nebraska: [
		"Colorado",
		"Iowa",
		"Minnesota",
		"Missouri",
		"Oklahoma",
		"Texas",
		"Wisconsin",
	],
	Nevada: ["Boise State", "UNLV"],
	"New Mexico": ["Arizona", "New Mexico State"],
	"New Mexico State": ["New Mexico", "UTEP"],
	"North Carolina": [
		"Duke",
		"East Carolina",
		"NC State",
		"South Carolina",
		"Virginia",
		"Wake Forest",
	],
	"NC State": [
		"Clemson",
		"Duke",
		"East Carolina",
		"North Carolina",
		"Wake Forest",
	],
	"North Texas": ["SMU"],
	"Northern Illinois": ["Ball State"],
	Northwestern: ["Illinois", "Michigan", "Notre Dame"],
	"Notre Dame": [
		"Army",
		"Boston College",
		"Michigan",
		"Michigan State",
		"Navy",
		"Northwestern",
		"Pittsburgh",
		"Purdue",
		"Stanford",
		"USC",
	],
	Ohio: ["Marshall", "Miami (OH)"],
	"Ohio State": ["Illinois", "Michigan", "Penn State"],
	Oklahoma: ["Missouri", "Nebraska", "Oklahoma State", "Texas"],
	"Oklahoma State": ["Oklahoma", "Texas Tech", "Tulsa"],
	"Old Dominion": ["Charlotte", "James Madison", "Liberty"],
	"Ole Miss": ["LSU", "Memphis", "Mississippi State"],
	Oregon: ["Oregon State", "Washington"],
	"Oregon State": ["Oregon"],
	"Penn State": [
		"Maryland",
		"Michigan State",
		"Minnesota",
		"Ohio State",
		"Pittsburgh",
		"Syracuse",
		"Temple",
	],
	Pittsburgh: [
		"Cincinnati",
		"Notre Dame",
		"Penn State",
		"Syracuse",
		"West Virginia",
	],
	Purdue: ["Illinois", "Indiana", "Notre Dame"],
	Rice: ["Houston", "SMU", "Tulsa"],
	Rutgers: ["Maryland"],
	"Sam Houston State": ["Texas State", "UTEP"],
	"San Diego State": ["Fresno State"],
	"San Jose State": ["Fresno State", "Hawaii", "Stanford"],
	SMU: ["Navy", "North Texas", "Rice", "TCU"],
	"South Alabama": ["Troy"],
	"South Carolina": [
		"Clemson",
		"Georgia",
		"Missouri",
		"North Carolina",
		"Texas A&M",
	],
	"South Florida": ["UCF"],
	"Southern Mississippi": ["Louisiana Tech", "Memphis", "Tulane", "UAB"],
	Stanford: ["California", "Notre Dame", "San Jose State", "USC"],
	Syracuse: ["Boston College", "Penn State", "Pittsburgh", "West Virginia"],
	TCU: ["Baylor", "SMU", "Texas", "Texas Tech"],
	Temple: ["Buffalo", "Penn State"],
	Tennessee: ["Alabama", "Florida", "Georgia", "Kentucky", "Vanderbilt"],
	Texas: ["Arkansas", "Nebraska", "Oklahoma", "TCU", "Texas A&M", "Texas Tech"],
	"Texas A&M": ["Arkansas", "Baylor", "LSU", "South Carolina", "Texas"],
	"Texas State": ["Sam Houston State", "UTSA"],
	"Texas Tech": ["Baylor", "Oklahoma State", "TCU", "Texas"],
	Toledo: ["Bowling Green"],
	Troy: ["Jacksonville State", "Middle Tennessee", "South Alabama", "UAB"],
	Tulane: ["LSU", "Southern Mississippi"],
	Tulsa: ["Houston", "Oklahoma State", "Rice"],
	UAB: ["Memphis", "Southern Mississippi", "Troy"],
	UCF: ["Cincinnati", "Connecticut", "South Florida"],
	UCLA: ["California", "USC"],
	UNLV: ["Hawaii", "Nevada"],
	USC: ["Notre Dame", "Stanford", "UCLA"],
	Utah: ["BYU", "Colorado", "Utah State"],
	"Utah State": ["BYU", "Utah", "Wyoming"],
	UTEP: ["New Mexico State", "Sam Houston State"],
	UTSA: ["Texas State"],
	Vanderbilt: ["Georgia Tech", "Kentucky", "Tennessee"],
	Virginia: ["Maryland", "North Carolina", "Virginia Tech"],
	"Virginia Tech": ["Georgia Tech", "Miami (FL)", "Virginia", "West Virginia"],
	"Wake Forest": ["Duke", "North Carolina", "NC State"],
	Washington: ["Oregon", "Washington State"],
	"Washington State": ["Washington"],
	"West Virginia": [
		"Louisville",
		"Marshall",
		"Pittsburgh",
		"Syracuse",
		"Virginia Tech",
	],
	"Western Kentucky": ["Middle Tennessee"],
	"Western Michigan": ["Central Michigan", "Eastern Michigan"],
	Wisconsin: ["Iowa", "Minnesota", "Nebraska"],
	Wyoming: ["BYU", "Colorado State", "Hawaii", "Utah State"],
};
